# tools.py
from logger_config import get_logger

def safe_math_eval(expression: str) -> str:
    logger = get_logger()
    
    # This log will automatically contain the Trace ID generated by the middleware!
    logger.info("tool_execution_started", tool="safe_math_eval", payload=expression)
    
    try:
        # ... math logic ...
        logger.info("tool_execution_success", result="40349683")
        return result
    except Exception as e:
        logger.error("tool_execution_error", error=str(e))
        return "Error"